[package]
name = "winit-input-map"
version = "0.1.0"
edition = "2021"
description = "Input Map for Winit"
license = "Apache-2.0 or MIT"
repository = "https://github.com/abss-witch/winit-input-map"
readme = "README.md"
keywords = ["winit", "input", "gamedev", "input"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium-types = { version = "0.1.0", optional = true }
winit = "0.29.15"
[lib]
path = "src/lib.rs"

[[example]]
name = "example"

[features]
glium-types = ["dep:glium-types"]
